#!/bin/sh
# Copyright (c) 2015 Bernhard Schmidt <Bernhard.Schmidt@lrz.de>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

if [ ! -d /run/systemd/system ]; then
	exit 0
fi

ACTIVE=`/bin/systemctl --no-legend | grep active | wc -l`
FAILED=`/bin/systemctl --no-legend --failed | wc -l`

STATUS=0
if [ "$FAILED" -gt 0 ]; then
    STATUS=2
fi

echo "$STATUS Services active=$ACTIVE|failed=$FAILED;1;1 $ACTIVE services active, $FAILED services failed"

